services:
  crm-api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: my-crm-api:prod
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - prod-network

networks:
  prod-network: